name: rentit
description: "a rental app"



version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image: ^4.3.0
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  flutter_advanced_drawer: ^1.3.6
  transparent_image: ^2.0.1
  image_picker: ^1.1.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  file_picker: ^8.1.3
  flutter_svg: ^2.0.13
  google_fonts: ^6.2.1
  firebase_storage: ^12.3.7
  geolocator: ^13.0.2
  firebase_app_check: ^0.3.1+7
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/logo/
    - assets/images/carousel/
    - assets/images/sidemenu/
    - assets/images/splash/



  # Uncomment and edit if you have custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
